// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIUserController is a mock of IUserController interface
type MockIUserController struct {
	ctrl     *gomock.Controller
	recorder *MockIUserControllerMockRecorder
}

// MockIUserControllerMockRecorder is the mock recorder for MockIUserController
type MockIUserControllerMockRecorder struct {
	mock *MockIUserController
}

// NewMockIUserController creates a new mock instance
func NewMockIUserController(ctrl *gomock.Controller) *MockIUserController {
	mock := &MockIUserController{ctrl: ctrl}
	mock.recorder = &MockIUserControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUserController) EXPECT() *MockIUserControllerMockRecorder {
	return m.recorder
}

// Ping mocks base method
func (m *MockIUserController) Ping(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", ctx)
}

// Ping indicates an expected call of Ping
func (mr *MockIUserControllerMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIUserController)(nil).Ping), ctx)
}

// SaveUser mocks base method
func (m *MockIUserController) SaveUser(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveUser", ctx)
}

// SaveUser indicates an expected call of SaveUser
func (mr *MockIUserControllerMockRecorder) SaveUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockIUserController)(nil).SaveUser), ctx)
}

// QueryUserByName mocks base method
func (m *MockIUserController) QueryUserByName(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueryUserByName", ctx)
}

// QueryUserByName indicates an expected call of QueryUserByName
func (mr *MockIUserControllerMockRecorder) QueryUserByName(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByName", reflect.TypeOf((*MockIUserController)(nil).QueryUserByName), ctx)
}

// UpdateUserByName mocks base method
func (m *MockIUserController) UpdateUserByName(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateUserByName", ctx)
}

// UpdateUserByName indicates an expected call of UpdateUserByName
func (mr *MockIUserControllerMockRecorder) UpdateUserByName(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByName", reflect.TypeOf((*MockIUserController)(nil).UpdateUserByName), ctx)
}

// RemoveUserByName mocks base method
func (m *MockIUserController) RemoveUserByName(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveUserByName", ctx)
}

// RemoveUserByName indicates an expected call of RemoveUserByName
func (mr *MockIUserControllerMockRecorder) RemoveUserByName(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserByName", reflect.TypeOf((*MockIUserController)(nil).RemoveUserByName), ctx)
}
