// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/zhulinwei/gin-demo/pkg/model"
	reflect "reflect"
)

// MockIUserService is a mock of IUserService interface
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// SaveUser mocks base method
func (m *MockIUserService) SaveUser(test1 model.UserReq) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", test1)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// SaveUser indicates an expected call of SaveUser
func (mr *MockIUserServiceMockRecorder) SaveUser(test1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockIUserService)(nil).SaveUser), test1)
}

// QueryUserByName mocks base method
func (m *MockIUserService) QueryUserByName(name string) model.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserByName", name)
	ret0, _ := ret[0].(model.User)
	return ret0
}

// QueryUserByName indicates an expected call of QueryUserByName
func (mr *MockIUserServiceMockRecorder) QueryUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByName", reflect.TypeOf((*MockIUserService)(nil).QueryUserByName), name)
}

// RemoveUserByName mocks base method
func (m *MockIUserService) RemoveUserByName(name string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserByName", name)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// RemoveUserByName indicates an expected call of RemoveUserByName
func (mr *MockIUserServiceMockRecorder) RemoveUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserByName", reflect.TypeOf((*MockIUserService)(nil).RemoveUserByName), name)
}

// UpdateUserByName mocks base method
func (m *MockIUserService) UpdateUserByName(oldName, newName string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByName", oldName, newName)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// UpdateUserByName indicates an expected call of UpdateUserByName
func (mr *MockIUserServiceMockRecorder) UpdateUserByName(oldName, newName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByName", reflect.TypeOf((*MockIUserService)(nil).UpdateUserByName), oldName, newName)
}
