// Code generated by MockGen. DO NOT EDIT.
// Source: test.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	gomock "github.com/golang/mock/gomock"
	dto "github.com/zhulinwei/gin-demo/pkg/dto"
	model "github.com/zhulinwei/gin-demo/pkg/model"
	mongo "go.mongodb.org/mongo-driver/mongo"
	reflect "reflect"
)

// MockITestDao is a mock of ITestDao interface
type MockITestDao struct {
	ctrl     *gomock.Controller
	recorder *MockITestDaoMockRecorder
}

// MockITestDaoMockRecorder is the mock recorder for MockITestDao
type MockITestDaoMockRecorder struct {
	mock *MockITestDao
}

// NewMockITestDao creates a new mock instance
func NewMockITestDao(ctrl *gomock.Controller) *MockITestDao {
	mock := &MockITestDao{ctrl: ctrl}
	mock.recorder = &MockITestDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockITestDao) EXPECT() *MockITestDaoMockRecorder {
	return m.recorder
}

// QueryUserByName mocks base method
func (m *MockITestDao) QueryUserByName(name string) model.Test {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserByName", name)
	ret0, _ := ret[0].(model.Test)
	return ret0
}

// QueryUserByName indicates an expected call of QueryUserByName
func (mr *MockITestDaoMockRecorder) QueryUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByName", reflect.TypeOf((*MockITestDao)(nil).QueryUserByName), name)
}

// SaveUser mocks base method
func (m *MockITestDao) SaveUser(test1 dto.Test) *mongo.InsertOneResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", test1)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	return ret0
}

// SaveUser indicates an expected call of SaveUser
func (mr *MockITestDaoMockRecorder) SaveUser(test1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockITestDao)(nil).SaveUser), test1)
}

// RemoveUserByName mocks base method
func (m *MockITestDao) RemoveUserByName(name string) *mongo.DeleteResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserByName", name)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	return ret0
}

// RemoveUserByName indicates an expected call of RemoveUserByName
func (mr *MockITestDaoMockRecorder) RemoveUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserByName", reflect.TypeOf((*MockITestDao)(nil).RemoveUserByName), name)
}

// UpdateUserByName mocks base method
func (m *MockITestDao) UpdateUserByName(oldName, newName string) *mongo.UpdateResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByName", oldName, newName)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	return ret0
}

// UpdateUserByName indicates an expected call of UpdateUserByName
func (mr *MockITestDaoMockRecorder) UpdateUserByName(oldName, newName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByName", reflect.TypeOf((*MockITestDao)(nil).UpdateUserByName), oldName, newName)
}
