// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/dao/user.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/zhulinwei/go-dc/pkg/model"
	mongo "go.mongodb.org/mongo-driver/mongo"
	reflect "reflect"
)

// MockIUserDao is a mock of IUserDao interface
type MockIUserDao struct {
	ctrl     *gomock.Controller
	recorder *MockIUserDaoMockRecorder
}

// MockIUserDaoMockRecorder is the mock recorder for MockIUserDao
type MockIUserDaoMockRecorder struct {
	mock *MockIUserDao
}

// NewMockIUserDao creates a new mock instance
func NewMockIUserDao(ctrl *gomock.Controller) *MockIUserDao {
	mock := &MockIUserDao{ctrl: ctrl}
	mock.recorder = &MockIUserDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUserDao) EXPECT() *MockIUserDaoMockRecorder {
	return m.recorder
}

// QueryUserByName mocks base method
func (m *MockIUserDao) QueryUserByName(name string) (*model.UserDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserByName", name)
	ret0, _ := ret[0].(*model.UserDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUserByName indicates an expected call of QueryUserByName
func (mr *MockIUserDaoMockRecorder) QueryUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByName", reflect.TypeOf((*MockIUserDao)(nil).QueryUserByName), name)
}

// QueryUsersByName mocks base method
func (m *MockIUserDao) QueryUsersByName(name string) ([]model.UserDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUsersByName", name)
	ret0, _ := ret[0].([]model.UserDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUsersByName indicates an expected call of QueryUsersByName
func (mr *MockIUserDaoMockRecorder) QueryUsersByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUsersByName", reflect.TypeOf((*MockIUserDao)(nil).QueryUsersByName), name)
}

// SaveUser mocks base method
func (m *MockIUserDao) SaveUser(user model.UserRequest) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", user)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser
func (mr *MockIUserDaoMockRecorder) SaveUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockIUserDao)(nil).SaveUser), user)
}

// BulkSaveUser mocks base method
func (m *MockIUserDao) BulkSaveUser(users []model.UserRequest) (*mongo.BulkWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSaveUser", users)
	ret0, _ := ret[0].(*mongo.BulkWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSaveUser indicates an expected call of BulkSaveUser
func (mr *MockIUserDaoMockRecorder) BulkSaveUser(users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSaveUser", reflect.TypeOf((*MockIUserDao)(nil).BulkSaveUser), users)
}

// RemoveUserByName mocks base method
func (m *MockIUserDao) RemoveUserByName(name string) (*mongo.DeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserByName", name)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserByName indicates an expected call of RemoveUserByName
func (mr *MockIUserDaoMockRecorder) RemoveUserByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserByName", reflect.TypeOf((*MockIUserDao)(nil).RemoveUserByName), name)
}

// UpdateUserByName mocks base method
func (m *MockIUserDao) UpdateUserByName(oldName, newName string) (*mongo.UpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByName", oldName, newName)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserByName indicates an expected call of UpdateUserByName
func (mr *MockIUserDaoMockRecorder) UpdateUserByName(oldName, newName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByName", reflect.TypeOf((*MockIUserDao)(nil).UpdateUserByName), oldName, newName)
}
